version: "3"

services:
  app:
    container_name: quickstart-server
    restart: always
    build: .
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "80:8082"
#      - ${EXPOSED_SERVER_PORT}:8082
    links:
      - mongo

  mongo:
    container_name: quickstart-mongo
    image: mongo
    restart: unless-stopped
#    volumes:
#      - ${MONGO_DATA_DB}:/data/db
    ports:
#      - ${EXPOSED_MONGO_PORT}:27017
      - "27017:27017"
    command: mongod --quiet --logpath /dev/null
