version: "3"
services:
  app:
    container_name: quickstart-server
    restart: always
    build: .
    ports:
      - '80:8082'
    links:
      - mongo
  mongo:
    container_name: quickstart-mongo
    image: mongo
    ports:
      - '27017:27017'
